<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.S3" Version="4.0.103.4" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
      <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.13" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
      <PackageReference Include="StackExchange.Redis" Version="3.3.1" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Email/Templates/*.html" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Drive.Application\Drive.Application.csproj" />
      <ProjectReference Include="..\Drive.Core\Drive.Core.csproj" />
    </ItemGroup>

</Project>
